### ISSUE TITLE
Segmentation fault when I run the patched vasp

### ISSUE THREAD

**Issue by zrqustc** [QuantumMaterialsModelling/UnfoldingPatch4vasp#1]
Dear developers,

When I run the patched vasp, I always met Segmentation fault as follows.
Do you have any suggestions about that?

 writing wavefunctions
 start k-points projection onto the first Brillouin zone of primitive cell.
 skip symmetry operation...
 K-point list is generated..
srun: error: nid003076: task 20: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=4721158.0
slurmstepd: error: *** STEP 4721158.0 ON nid002312 CANCELLED AT 2023-01-15T15:57:19 ***
srun: error: nid002644: task 10: Segmentation fault
srun: error: nid003424: task 28: Segmentation fault
srun: error: nid002313: task 5: Segmentation fault
srun: error: nid002645: task 14: Segmentation fault
srun: error: nid003073: task 16: Segmentation fault
srun: error: nid003421: task 24: Segmentation fault
srun: error: nid002645: tasks 13,15: Segmentation fault
srun: error: nid002644: task 11: Segmentation fault
srun: error: nid003424: task 31: Segmentation fault
srun: error: nid003076: task 21: Segmentation fault
srun: error: nid002313: task 4: Segmentation fault
srun: error: nid002644: task 9: Segmentation fault
srun: error: nid003073: tasks 18-19: Segmentation fault
srun: error: nid003424: task 29: Segmentation fault
srun: error: nid003076: task 23: Segmentation fault
srun: error: nid002313: task 7: Segmentation fault
srun: error: nid003421: tasks 25,27: Segmentation fault
srun: error: nid003424: task 30: Segmentation fault
srun: error: nid003076: task 22: Segmentation fault
srun: error: nid003073: task 17: Segmentation fault
srun: error: nid002313: task 6: Segmentation fault
srun: error: nid002644: task 8: Segmentation fault
srun: error: nid002645: task 12: Segmentation fault
srun: error: nid003421: task 26: Segmentation fault
srun: error: nid002312: task 0: Terminated
srun: error: nid002312: tasks 1-3: Segmentation fault
srun: Force Terminated StepId=4721158.0

**Comment by zrqustc** [comment]
For vasp CPU version, I met this following errors:


POSCAR.prim and CONTCAR.prim created successfully
 writing procar
forrtl: severe (153): allocatable array or pointer is not allocated
Image              PC                Routine            Line        Source
vasp_std           0000000001AC2ED4  for_dealloc_alloc     Unknown  Unknown
vasp_std           0000000000EB31AB  Unknown               Unknown  Unknown
vasp_std           0000000001A4B813  Unknown               Unknown  Unknown
vasp_std           0000000000419562  Unknown               Unknown  Unknown
libc-2.28.so       00001494CA4344A3  __libc_start_main     Unknown  Unknown
vasp_std           000000000041946E  Unknown               Unknown  Unknown
forrtl: severe (153): allocatable array or pointer is not allocated
Image              PC                Routine            Line        Source
vasp_std           0000000001AC2ED4  for_dealloc_alloc     Unknown  Unknown
vasp_std           0000000000EB31AB  Unknown               Unknown  Unknown
vasp_std           0000000001A4B813  Unknown               Unknown  Unknown
vasp_std           0000000000419562  Unknown               Unknown  Unknown
libc-2.28.so       000014C049EB74A3  __libc_start_main     Unknown  Unknown
vasp_std           000000000041946E  Unknown               Unknown  Unknown
forrtl: severe (153): allocatable array or pointer is not allocated

**Comment by MicheleReticcioli** [comment]
Dear Ruiqi,
unfortunately, we have not experienced such issue. Have you managed to successfully run the simple examples in the documentation?

**Comment by zrqustc** [comment]
Yes, I have run a simple case successfully.

**Comment by MicheleReticcioli** [comment]
It could be a memory issue then. One attempt you could make is to use more memory per core (usually on HPC you can use less cores per node, making the memory per core higher). Otherwise, you could try, just as a test, to reduced the computationally demanding parameters in your calculations (e.g., ENCUT, k-points).
If not a memory problem, then it could also be a problem with the compiling of VASP: have you used the matching patch for your VASP version?
